services:
  app:
    container_name: handson-202605-04-performance-02-large-data
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_PATH=/workspace/data/database.sqlite
    volumes:
      - ./app:/workspace/app
      - ./scripts:/workspace/scripts
      - ./data:/workspace/data
      - /workspace/node_modules
