services:
  app:
    container_name: handson-202605-04-performance-03-cache
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_PATH=/workspace/data/database.sqlite
    volumes:
      - ./data:/workspace/data
    develop:
      watch:
        - action: sync+restart
          path: ./app
          target: /workspace/app
        - action: sync+restart
          path: ./scripts
          target: /workspace/scripts
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./Dockerfile
